### PR TITLE
Modernize site using bootstrap

### PR DESCRIPTION
**Pull request by CaselIT**
this is a wip atm

cc @zzzeek @jvanasco

### CODE REVIEW

**Comment by CaselIT** [comment]
a first pass should be mostly done

**Comment by jvanasco** [comment]
It’s a holiday here through Monday, but I’m excited to dig into this on Tuesday.

**Comment by zzzeek** [comment]
I did a build and there's lots and lots that is wrong here:

1. fonts got removed (Source Sans Pro, it seems to be renedering in a default browser font now)
2. colors in the nav got lost
3. box shadows in nav got lost
4. window grow/shrink got lost  (will attach screen shots)

**Comment by zzzeek** [comment]
for window grow shrink model, see attached screenshots - when browser window is narrowed, the borders should gracefully shrink to zero to maximize space - i emulated this from the mysql.org docs site

**Comment by zzzeek** [comment]
this one w/ excessive borders for smaller window:

Screenshot from 2021-07-05 13-07-57


current site w/ borders that collapse when window is shrunk:

Screenshot from 2021-07-05 13-08-28

**Comment by zzzeek** [comment]
here's the horizontal growth difference recorded from my phone to screen

jumping growth, with border pushing its way in (excuse my chatter in this)

https://youtu.be/toGLrUWE7Q4

smooth growth with eager fill of screen borders, but when there is a border it still is smooth.  I copied from the way https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html works

https://youtu.be/-C-aUQkDrtc


if we can make it work like the latter that would be good, I put a lot of effort into that and I'd hate to lose it

**Comment by CaselIT** [comment]
I think we can reduce the number of times it will adjust the layout, but I think it's inevitable to have it move around while changing the width, since it needs to physically change the layout of the page. Also the mysql docs does that 2 or 3 times

**Comment by zzzeek** [comment]
am I just not noticing it because of the wider width ?

**Comment by jvanasco** [comment]
Is this still the build instructions?  (from gitter a few weeks ago)

```
#!/bin/bash

virtualenv .venv
source .venv/bin/activate
pip install git+https://github.com/sqlalchemyorg/zeekofile
git clone https://github.com/sqlalchemyorg/sqlalchemyorg
cd sqlalchemyorg/
pip install -r requirements.txt
zeekofile --serve
```

**Comment by zzzeek** [comment]
> Is this still the build instructions? (from gitter a few weeks ago)
> 
> ```
> #!/bin/bash
> 
> virtualenv .venv
> source .venv/bin/activate
> pip install git+https://github.com/sqlalchemyorg/zeekofile
> git clone https://github.com/sqlalchemyorg/sqlalchemyorg
> cd sqlalchemyorg/
> pip install -r requirements.txt
> zeekofile --serve
> ```

yes

**Comment by CaselIT** [comment]
@zzzeek could you take another look? thanks

**Comment by zzzeek** [comment]
it's on my list....lawn mowing time

**Comment by CaselIT** [comment]
> 
> 
> it's on my list....lawn mowing time

my robot is always at work 🤖😂

**Comment by zzzeek** [comment]
OK:

page grow / shrink behavior: looks fine now, howd you fix that?

fonts: source sans pro is back, that's good
fonts in nav bar seem 2px smaller now, they seem too small, they were 18px before now 16

line height in nav has grown, that seems to be accomodated by a thicker nav bar, might be fine, dropdowns grow vertically as a result, might be fine but need to see larger fonts again

the headers in the sitebar on the main site use the "dejavu sans" font, not the source sans pro.   "dejavu sans" with capitalized is for all headers.  if we want to change that, fine but all the headers should be treated under the same style, i notice dejavu sans *is* still used in the main pages for headers

boxes:  just check out the border style in "Current Releases" in https://www.sqlalchemy.org/  it's got a slight drop shadow effect on the right / bottom that is separate from top/left

**Comment by CaselIT** [comment]
> page grow / shrink behavior: looks fine now, howd you fix that?

that's the expected behavior of the container classes. I'm now using the larger one since it better matched the current site, so that only a step is done. We can probably remove that also using the fluid container with a max width.

> fonts in nav bar seem 2px smaller now, they seem too small, they were 18px before now 16

I've yet to look at font sizes, so it may be that other element have different fonts.
Regarding the other remarks on font I'll look at them

> boxes: just check out the border style in "Current Releases" in https://www.sqlalchemy.org/ it's got a slight drop shadow effect on the right / bottom that is separate from top/left

it has that also the update but it's a bit less visible. will look at making it a bit more visible.

**Comment by CaselIT** [comment]
@zzzeek should have fixed the fonts and the other points.

I've also fixed an issue with the section that in the blog did not pass the section correctly

**Pull request closed without merging**
