### PR TITLE
Limit page width

### PR DESCRIPTION
**Pull request by bourke**
Fix for #6

### CODE REVIEW

**Comment by zzzeek** [comment]
tried to find you on IRC.   this looks great!  thanks for all this effort!  I have to find time to build and see how it looks.   ok let me try it now.

**Comment by zzzeek** [comment]
so it works really well but it seems narrow to me.    obvisouly I dont know anything about design.  but what am I seeing when I look at mysql's site?   at https://dev.mysql.com/, we see the nav bar and the whole thing expands to a pretty large width, it looks like 1600 pixels, which appears to be what I have on my site right now.   why is mysql's site not getting the same complaint that I did in #6 ?

**Comment by zzzeek** [comment]
What I see at :

https://dev.mysql.com/doc/refman/8.0/en/mysql-cluster.html

compared to:

https://docs.sqlalchemy.org/en/14/core/tutorial.html

is:

1. wider left nav

2. much nicer font on mysql's site with wider font spacing, leading ?

3. more spacing betewen things, like the spacing around their "Important" note has a nice padding on the left as well as top/bottom, unlke our green dragon boxes that look very tight

4. way slicker nav controls etc on mysql

did the refactor here make it easier for me to control the knobs basically?   im sure you can imagine that when I got all this working, if I changed one number the whole thing would blow up.

**Comment by zzzeek** [comment]
OK i have some ideas, ill merge this but I'm expanding it back to 1600 , so, mostly a little formatting cleanup.   the fixes are more on the zzzeeksphinx side to make things less cluttered.

**Comment by zzzeek** [comment]
this is merged.    I made the sidebar wider at https://docs.sqlalchemy.org/en/14/orm/extensions/declarative/relationships.html, which now looks a little awkward because the layout hasn't adjusted that well, and made the font a little bigger with more spacing, as well as on the main site https://www.sqlalchemy.org/ which looks a little nicer.  thanks!

**Comment by bourke** [comment]
Changes were pretty minor — took so long because despite my best efforts, I couldn't get the CSS reflected in the sqlalchemy docs (much fidgeting with RTD_BASE_URL, no joy). Happy to refine further if I can get that working.

**Comment by zzzeek** [comment]
I guess I should figure out how to get the site / docs unified now that they are hosted on the same server again.  but it took so much work to make it work the way it does now I can't even get my head around it.  just so  you dont feel bad I couldn't even comfortably test the thing locally, had to build the sphinx side and copy the files every time.   that's kind of how it has to be w/ the sphinx though unless I build a huge new extension to zeekofile i guess...im too busy

**Comment by zzzeek** [comment]
basically mysql's site has what I think works really well if not the best actual database.   so im just ripping that off in my amateurish way

**Comment by zzzeek** [comment]
but you *HAVE* to be impressed with my vertical scrolling model for the sidebar + the contextual highlighting, that is my most amazing web achievement ever.

**Pull request closed without merging**
