### PR TITLE
50/50 split with EA / carbon

### PR DESCRIPTION
**Pull request by zzzeek**

### CODE REVIEW

**Review by CaselIT — APPROVED** [review]
looks ok!

**Comment by CaselIT** [comment]
interesting. `bannerads.css` is on easy list and it's filtered by it

**Comment by zzzeek** [comment]
uh what?  filename is a banned name?

**Comment by zzzeek** [comment]
renamed it

**Comment by zzzeek** [comment]
yes they are both blocked by a lot of blockers anyway

**Comment by CaselIT** [comment]
The site also seems to ask for a default css that's not found and it's redirected to notfound.html

**Comment by CaselIT** [comment]
that seems in sphinx only. the main site does not ask if

**Comment by zzzeek** [comment]
if you can show me a firefox debug network , I see default.css with 200 return code

**Comment by CaselIT** [comment]
just open https://docs.sqlalchemy.org/en/20/. You will get a 302 on default.css redirecting to notfound.html, but firefox complains because notfound.html is a text/html not a text/css as expected

**Comment by zzzeek** [comment]
i am not getting that, here is what im getting

image

**Comment by zzzeek** [comment]
you know what that is, I think sphinx at some point added that file and we dont actually have "default.css"

yeah that's in our plain sphinx build also.  whatever version of sphinx we upgraded to is just hardcoding that file, we dont have it

**Comment by CaselIT** [comment]
Same as my requests.
The issue here I this this:
- in zzzsphinx there is still a reference to default.css as a style sheet
- there is no longer a default.css on the site
- Apache finds nothing, so it redirects to notfound (since I guess it's the default redirect it has)
- it returns is as an html page, since what's it is
- firefox complaints since it expected a css and got an html back

Overall not a particular issue, just something to cleanup

**Comment by CaselIT** [comment]
> you know what that is, I think sphinx at some point added that file and we dont actually have "default.css"
> 
> yeah that's in our plain sphinx build also. whatever version of sphinx we upgraded to is just hardcoding that file, we dont have it

Ok, I'll take a look if it's in zzzsphinx, if it comes from sphinx directly I'll create an empty file for it

**Comment by zzzeek** [comment]
this has been in our source code in conf.py for decades:

```py
# The style sheet to use for HTML and HTML Help pages. A file of that name
# must exist either in Sphinx' static/ path, or in one of the custom paths
# given in html_static_path.
html_style = "default.css"

```

however, in an old doc build, like 1.2, it's not in the CSS.   It looks like sphinx at some point began adding this file to the standard sphinx css files.    We dont need it so solution is to remove this line in conf.py, assuming that doesnt break sphinx

**Comment by CaselIT** [comment]
Just doing the empty file is also an option in anything breaks :)

**Comment by zzzeek** [comment]
i can remove it from conf.py and it is fine, does not come out in the file anymore.

but there are also some other issues with this autogenerated list I have to fix, we would assume newer sphinx releases at some point broke things, right now it's this:

```html
<!-- begin iterate through site-imported + sphinx environment css_files -->
                <link rel="stylesheet" href="[_static/pygments.css](view-source:http://localhost:8080/_static/pygments.css)" type="text/css" />
                <link rel="stylesheet" href="[_static/pygments.css](view-source:http://localhost:8080/_static/pygments.css)" type="text/css" />
                <link rel="stylesheet" href="[_static/docs.css](view-source:http://localhost:8080/_static/docs.css)" type="text/css" />
                <link rel="stylesheet" href="[_static/copybutton.css](view-source:http://localhost:8080/_static/copybutton.css)" type="text/css" />
                <link rel="stylesheet" href="[_static/docs.css](view-source:http://localhost:8080/_static/docs.css)" type="text/css" />
                <link rel="stylesheet" href="[_static/changelog.css](view-source:http://localhost:8080/_static/changelog.css)" type="text/css" />
                <link rel="stylesheet" href="[_static/sphinx_paramlinks.css](view-source:http://localhost:8080/_static/sphinx_paramlinks.css)" type="text/css" />
            <!-- end iterate through site-imported + sphinx environment css_files -->
```

**Comment by zzzeek** [comment]
uh minus the "view source" crap which seems to be copy and paste stuff..it's repeating the css files is the point

**Comment by zzzeek** [comment]
ok the pygments.css is a rule in zeeksphinx, the docs.css being repeated it seems the removal of "default.css" makes "docs.css" come out twice somehow

**Comment by CaselIT** [comment]
let me know if you want me to do something here

**Pull request merged**
